package toolbox.tivo;

import java.io.IOException;

/**
 * Simple interface for transcoder implementations to adhere to. 
 */
public interface ITranscoder {
    
    /**
     * Transcodes a movie.
     * 
     * @param movieInfo Source movie information.
     * @param destFilename Name of the file to write the transcoded movie to.
     * @throws IOException on I/O error.
     * @throws InterruptedException on error.
     */
    void transcode(MovieInfo movieInfo, String destFilename)
        throws IOException, InterruptedException;
    
    
    /**
     * Subscribes a listener to the events generated by this trancoder.
     * 
     * @param listener Listener to add.
     */
    void addTranscoderListener(ITranscoderListener listener);
    
    
    /**
     * Unsubscribes a listener from the events generated by this transcoder.
     * 
     * @param listener Listener to remove.
     */
    void removeTranscoderListener(ITranscoderListener listener);
}