package toolbox.util.ui.tabbedpane;

/**
 * Listener for events generated by JSmartTabbedPane 
 */
public interface SmartTabbedPaneListener
{
    /**
     * Notification that a tab is about to close.
     * 
     * @param tabbedPane Tabbed pane associated with the tab
     * @param tabIndex Tab index starting at zero
     */
    public void tabClosing(JSmartTabbedPane tabbedPane, int tabIndex);
}
