package toolbox.util.dirmon.event;

import toolbox.util.dirmon.DirectoryMonitor;
import toolbox.util.dirmon.FileSnapshot;


/**
 * Event generated by a {@link toolbox.util.dirmon.DirectoryMonitor} that 
 * conveys the creation, deletion, or update of a file. 
 */
public class FileEvent extends BaseEvent {

    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------
    
    public static final int TYPE_FILE_CREATED = 0;
    public static final int TYPE_FILE_CHANGED = 1;
    public static final int TYPE_FILE_DELETED = 2;
    public static final int TYPE_FILE_CREATION_FINISHED = 3;

    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------
    
    private FileSnapshot beforeSnapshot_;
    private FileSnapshot afterSnapshot_;
    
    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------
    
    public FileEvent(
        int eventType,
        DirectoryMonitor source, 
        FileSnapshot before, 
        FileSnapshot after) {
        
        super(eventType, source);
        beforeSnapshot_ = before;
        afterSnapshot_ = after;
    }

    // -------------------------------------------------------------------------
    // Public
    // -------------------------------------------------------------------------
    
    public FileSnapshot getBeforeSnapshot() {
        return beforeSnapshot_;
    }

    public FileSnapshot getAfterSnapshot() {
        return afterSnapshot_;
    }
}