package toolbox.util.dirmon.event;

import toolbox.util.dirmon.DirectoryMonitor;
import toolbox.util.dirmon.event.BaseEvent;

/**
 * Event generated by a {@link toolbox.util.dirmon.DirectoryMonitor} that 
 * contains a status change. 
 */
public class StatusEvent extends BaseEvent {

    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------
    
    public static final int TYPE_START_SCAN = 100;
    public static final int TYPE_END_SCAN = 101;
    
    public static final int TYPE_START_DISCOVERY = 102;
    public static final int TYPE_END_DISCOVERY = 103;
    
    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------
    
    private String message_;
    
    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------
    
    public StatusEvent(
        int eventType,
        DirectoryMonitor source, 
        String message) {
        
        super(eventType, source);
        message_ = message;
    }

    // -------------------------------------------------------------------------
    // Public
    // -------------------------------------------------------------------------
    
    public String getMessage() {
        return message_;
    }
}