package toolbox.util.dirmon.event;

import java.util.EventObject;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import toolbox.util.dirmon.DirectoryMonitor;

/**
 * Base event class for all events generated by a
 * {@link toolbox.util.dirmon.DirectoryMonitor}.
 */
public class BaseEvent extends EventObject {

    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------
    
    /**
     * Type of event. Make sure values do not overlap in subclasses.
     */
    private int eventType_;
    
    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------
    
    public BaseEvent(int eventType, DirectoryMonitor source) { 
        super(source);
        eventType_ = eventType;
    }

    // -------------------------------------------------------------------------
    // Public
    // -------------------------------------------------------------------------
    
    /**
     * Returns event type.
     * 
     * @return int
     */
    public int getEventType() {
        return eventType_;
    }

    /**
     * Convenience method that returns the DirectoryMonitor which is the
     * source of this event.
     *  
     * @return DirectoryMonitor
     */
    public DirectoryMonitor getDirectoryMonitor() {
        return (DirectoryMonitor) getSource();
    }
    
    // -------------------------------------------------------------------------
    // Overrides java.lang.Object
    // -------------------------------------------------------------------------
    
    public String toString(){
        return ToStringBuilder.reflectionToString(
            this, ToStringStyle.MULTI_LINE_STYLE);
    }
}