package toolbox.tunnel;

/**
 * Listener for events generated by a TcpTunnel
 */
public interface TcpTunnelListener
{
    /**
     * Notification that the internal status of the tunnel has changed
     * 
     * @param  tunnel  Source tunnel
     * @param  status  New status
     */
    public void statusChanged(TcpTunnel tunnel, String status);
}
