package toolbox.util.dirmon;

import java.util.EventObject;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * Event generated by a {@link toolbox.util.dirmon.DirectoryMonitor} that 
 * conveys the creation, deletion, or update of a file. 
 */
public class DirectoryMonitorEvent extends EventObject {

    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------
    
    public static final int TYPE_CREATED = 0;
    public static final int TYPE_CHANGED = 1;
    public static final int TYPE_DELETED = 2;
    
    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------
    
    private int eventType_;
    private FileSnapshot beforeSnapshot_;
    private FileSnapshot afterSnapshot_;
    
    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------
    
    public DirectoryMonitorEvent(
        int eventType,
        DirectoryMonitor source, 
        FileSnapshot before, 
        FileSnapshot after) {
        
        super(source);
        eventType_ = eventType;
        beforeSnapshot_ = before;
        afterSnapshot_ = after;
    }

    // -------------------------------------------------------------------------
    // Public
    // -------------------------------------------------------------------------
    
    public FileSnapshot getBeforeSnapshot() {
        return beforeSnapshot_;
    }

    public FileSnapshot getAfterSnapshot() {
        return afterSnapshot_;
    }

    public int getEventType() {
        return eventType_;
    }
    
    public String toString(){
        return ToStringBuilder.reflectionToString(
            this, ToStringStyle.MULTI_LINE_STYLE);
    }
}