package toolbox.tivo;

/**
 * Interface that describes events generated by a transcoder. 
 */
public interface ITranscoderListener {

    void transcodeStarted(ITranscoder transcoder);
    
    void transcodeFinished(ITranscoder transcoder);
    
    void transcodeProgress(ITranscoder transcoder);
    
    void transcodeError(ITranscoder transcoder);
}
