package toolbox.util.ui.tabbedpane;

/**
 *  Listener for events generated by JSmartTabbedPane 
 */
public interface SmartTabbedPaneListener
{
    public void tabClosing(JSmartTabbedPane tabbedPane, int tabIndex);
}
