package toolbox.util.ui.font;

/**
 * Interface exposing events generated by the font selection dialog
 */
public interface IFontDialogListener
{
	/**
	 * Called when the OK button is pressed
	 * 
	 * @param  fontPanel  Font selection panel
	 */
    public void okButtonPressed(FontSelectionPane fontPanel);
    
	/**
	 * Called when the cancel button is pressed
	 * 
	 * @param  fontPanel  Font selection panel
	 */
    public void cancelButtonPressed(FontSelectionPane fontPanel);
    
    
   	/**
	 * Called when the apply button is pressed
	 * 
	 * @param  fontPanel  Font selection panel
	 */
	public void applyButtonPressed(FontSelectionPane fontPanel);
}
